Fix variable interpolation
Thream/styled-jsx-plugin-sass pull request #102
Opened 2021-11-15 06:37 UTC by SwiftWinds

fixes #101

I changed the regex to also allow for matching a whitespace. This guarantees that this matches cases where the variable is not interpolated as the last word in the line, but rather somewhere in the middle of the line, which was the edge case mentioned in #101 (and actually the same edge case as https://github.com/giuseppeg/styled-jsx-plugin-sass/issues/32#issuecomment-672846776 from the original repo that this fork originated).

2021-11-18 07:00 UTC, Divlo requested changes
Thanks for your PR! @SwiftWinds 

Could you add a test case, so we can avoid regression?

2021-11-18 07:30 UTC, SwiftWinds commented
Sure! will do :)

2021-11-21 03:01 UTC, SwiftWinds commented
I added tests. Please let me know if they suffice :)

2021-11-21 07:12 UTC, Divlo approved these changes
LGTM! :+1:

2021-11-21 07:12 UTC, merged

2021-11-21 10:49 UTC, SwiftWinds commented
Thanks :)